### ISSUE TITLE
One week experience report

### ISSUE THREAD

**Issue by shumi2nd** [yuenm18/ooxml-viewer-vscode#13]
**Hello**, it's me again. I have been experiencing this plugin for several days. This plugin is really great and has greatly improved my learning efficiency.Thank u very much!😊
Then feedback a small problem: XML file formatting.When encountered with "/ >"The ending single-line label is mistakenly formatted into two lines and incorrectly indented.The current solution is to work with [this plugin](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml).
But my ability is limited, so maybe you can perfect it in the next version.😊

**Comment by mikeebowen** [comment]
@shumi2nd Could you please send a sample of how the viewer is formatting the xml currently and also how you think it should be formatted.

Thanks!

**Comment by shumi2nd** [comment]
The first image is a formatting style opened using your plugin
![img01](https://user-images.githubusercontent.com/19216020/104668250-b4d7c700-5712-11eb-9f33-f2fe1b64026a.png)

The second image shows the effect of additional use of the [RedHat XML plug-in](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml)
![img02](https://user-images.githubusercontent.com/19216020/104668258-bacda800-5712-11eb-86e4-925a0dd8452f.png)

😊😊

**Comment by shumi2nd** [comment]
The last few lines were incorrectly indented.

**Comment by mikeebowen** [comment]
Thanks for sending the images, I see what you mean now. 

We use a package, [vkbeautify](https://github.com/aabluedragon/vkbeautify), to format and minify the xml parts. We chose it, because it is the most efficient xml formatter we could find. It is a very opinionated formatter however, so there is no config option to format the xml parts like it is in your second image, so we aren't going to be able to change the formatting in the way you describe. 

The xml is only formatted to make it more readable though. Any formatting is removed, because the xml is minified before updating the OOXML Document, so the format before being minified does not have an effect on what is written to the OOXML document, so if you're worried that incorrect data will be written to the OOXML document that is taken care of by the minimization.

Thanks for your support and please continue to submit any issues or questions 😃 😃
